ansible_become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636330653830376133656135653263336333326439616464666363396137373739653235656366
          3738343330623437303530316665393736346265316332390a323333303239326461653331653832
          37356237313031656366383238373231383533333439636266393730666263353833383133313237
          6263396530366662620a383137313638363963336161656239623063353731663565623931303934
          3665